import {projectEvidence} from './projectEvidence';

// Values transcribed from the owner's public reports; these are not fresh benchmarks.
export default function EvidencePanel({id}:{id:string}){
 if(!['drax','emotion','airspace'].includes(id))return null;
 const source=projectEvidence[id].url;
 return <aside className="evidence-panel" aria-label="Project evidence">
 <div className="evidence-heading"><span className="eyebrow">FROM THE SOURCE</span><a href={source} target="_blank" rel="noreferrer">Inspect the work ↗</a></div>
 {id==='drax'?<><h3>A tutor with an explicit fallback.</h3><p className="evidence-context">PDF ingestion, semantic retrieval and context assembly feed a local LLM. The chat service retrieves up to eight chunks per question.</p><blockquote>“No textbook is loaded. Please upload a textbook to get answers from it.”</blockquote><p className="evidence-caption">Actual strict-mode response defined in the source, not a live model demonstration.</p><div className="evidence-notes"><p><strong>The decision</strong>Strict and general tutor modes separate textbook-only instructions from answers that may use general knowledge.</p><p><strong>The limitation</strong>Page metadata is estimated from chunk order. Citations need page-aware ingestion and grounding evaluation before they can be trusted as precise references.</p></div><a className="text-link" href={source+'/blob/main/backend/app/services/rag_agent.py'} target="_blank" rel="noreferrer">Read the retrieval service ↗</a></>:id==='emotion'?<><h3>Accuracy is only part of the result.</h3><div className="result-bars" aria-label="README-reported accuracy by architecture">{[['VGG16',97.85],['DenseNet121',96.04],['ResNet50',85.57],['MobileNetV2',74.74]].map(([name,value])=><div key={name}><span>{name}</span><i><b style={{width:value+'%'}}/></i><strong>{value}%</strong></div>)}</div><p className="evidence-caption">Reported accuracy · curated happy/sad image study · values from the repository README.</p><div className="evidence-notes"><p><strong>The experiment</strong>Four transfer-learning architectures compared for a two-class task, with image cleaning, normalization and augmentation.</p><p><strong>The open question</strong>The README separately reports F1 0.5627 and AUC 0.5021. Their evaluation basis needs reconciliation with headline accuracy; this is not evidence of reliable general emotion recognition.</p></div></>:<><h3>22 years of flight records. Three analytical jobs.</h3><div className="flight-evidence"><a href={`${import.meta.env.BASE_URL}evidence/flight-scaling.png`} target="_blank" rel="noreferrer"><img src={`${import.meta.env.BASE_URL}evidence/flight-scaling.png`} alt="Published table and chart of flight-data processing times on 12 nodes" loading="lazy"/></a><div><span className="eyebrow">PUBLISHED 12-NODE RUN</span><p className="evidence-measure">170 → 307 <small>seconds</small></p><p>From one year to 22 years of data in the published scaling report.</p><p className="evidence-caption">Original project artifact. Not independently rerun; repeated-run variance is not supplied.</p></div></div><div className="evidence-notes"><p><strong>The workload</strong>Java MapReduce jobs examine punctuality, airport taxi times and cancellation reasons.</p><p><strong>The boundary</strong>The published Oozie XML leaves later job configurations as placeholders. Those settings need completing before deployment.</p></div></>}
 </aside>
}
