// Public repositories supplied by the portfolio owner, reviewed 2026-09-11.
export const projectEvidence:Record<string,{url:string;scope:string;fact:string;artifact?:string}>={
 drax:{url:'https://github.com/nymav/drax_tbs',scope:'PDF ingestion, semantic retrieval, local model integration, and a React tutoring interface.',fact:'Textbook upload, saved chat sessions, and configurable tutor roles are documented in the repository.'},
 dachat:{url:'https://github.com/nymav/DaChat',scope:'CSV exploration with local language-model responses and property-price prediction.',fact:'The documented workflow combines natural-language data questions with a trained price model.'},
 emotion:{url:'https://github.com/nymav/Face-Emotion-Detection-Using-CNNs',scope:'Image preparation, transfer-learning comparisons, and evaluation for happy/sad classification.',fact:'Four CNN architectures compared across two emotion classes; evaluation plots and results are in the notebook.',artifact:'https://github.com/nymav/Face-Emotion-Detection-Using-CNNs/blob/main/DRAX_CODE.ipynb'},
 ddos:{url:'https://github.com/nymav/DDoS-Attack-Detection-using-Machine-Learning',scope:'Traffic preprocessing, classifier comparison, and a desktop interface.',fact:'The published experiment uses the KDD Cup 1999 dataset and includes training and comparison scripts.'},
 market:{url:'https://github.com/nymav/Predictive-Modeling-for-Optimizing-Bank-Marketing-Campaigns-Using-Machine-Learning',scope:'Exploratory analysis and classification of term-deposit subscriptions.',fact:'The repository documents 45,211 client records and 16 features. SHAP interpretation is listed as future work.',artifact:'https://github.com/nymav/Predictive-Modeling-for-Optimizing-Bank-Marketing-Campaigns-Using-Machine-Learning/blob/main/final.ipynb'},
 airspace:{url:'https://github.com/nymav/Fligh-Data-Analysis-with-MapReduce',scope:'Java MapReduce jobs coordinated with Hadoop and an Oozie workflow.',fact:'Three jobs analyze 22 years of flight records for punctuality, taxi times, and cancellations.',artifact:'https://github.com/nymav/Fligh-Data-Analysis-with-MapReduce/blob/main/output.txt'}
};
